version: '3.8'

services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd /app && PYTHONPATH=/app pytest tests/ -v --asyncio-mode=auto"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
      DATABASE_URL: "sqlite://:memory:"
      REDIS_URL: "redis://redis:6379"
      TEST_MODE: "true"
      JWT_SECRET_KEY: "test_secret_key_123"
      JWT_ALGORITHM: "HS256"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 